CREATE DATABASE THECOFFEEHOUSE
GO

USE THECOFFEEHOUSE
GO

CREATE TABLE NHANVIEN (
	manv VARCHAR(10) PRIMARY KEY,
	ho NVARCHAR(30),
	ten NVARCHAR(10) NOT NULL,
	gioitinh NVARCHAR(5),
	vitri NVARCHAR(20),
	luong INT NOT NULL,
	ngayvaolam DATE NOT NULL,
	sdt VARCHAR(50) NOT NULL,
	email VARCHAR(50),
	macn_thuocve VARCHAR(10) NOT NULL,
	maca VARCHAR(6) NOT NULL
);

CREATE TABLE CHINHANH (
	macn VARCHAR(10) PRIMARY KEY,
	tencn NVARCHAR(50) NOT NULL,
	diachi NVARCHAR(100) NOT NULL,
)

CREATE TABLE CALAMVIEC (
	maca VARCHAR(6) PRIMARY KEY,
	tenca NVARCHAR(30) NOT NULL,
	thoigianbd TIME(0) NOT NULL,
	thoigiankt TIME(0) NOT NULL,
	sotien INT NOT NULL
)

CREATE TABLE TAIKHOAN (
	stk VARCHAR(15) PRIMARY KEY,
	matkhau VARCHAR(20) NOT NULL,
	manv VARCHAR(10) NOT NULL
)

CREATE TABLE TONKHO (
	stt_tk INT IDENTITY(1, 1) PRIMARY KEY,
	sl_hangton INT,
	manl VARCHAR(10) NOT NULL
)

CREATE TABLE NGUYENLIEU (
	manl VARCHAR(10) PRIMARY KEY,
	tennl NVARCHAR(50) NOT NULL,
	donvitinh NVARCHAR(10) NOT NULL
)

CREATE TABLE XUAT_NL (
	stt_xuat INT IDENTITY(1, 1) PRIMARY KEY,
	sl_xuat INT,
	ngayxuat DATE,
	manl VARCHAR(10) NOT NULL
)

CREATE TABLE CHITIETPN (
	stt_pn INT IDENTITY(1, 1) PRIMARY KEY,
	slpn INT NOT NULL,
	sotien INT NOT NULL,
	manl VARCHAR(10) NOT NULL,
	mapn VARCHAR(10) NOT NULL
)

CREATE TABLE PHIEUNHAP (
	mapn VARCHAR(10) PRIMARY KEY,
	ngaypn DATE NOT NULL,
	mancc VARCHAR(10) NOT NULL
)

CREATE TABLE NHACUNGCAP (
	mancc VARCHAR(10) PRIMARY KEY,
	tenncc NVARCHAR(100) NOT NULL,
)

CREATE TABLE DIACHINCC (
	mancc VARCHAR(10) NOT NULL,
	diachi NVARCHAR(100) NOT NULL,
	CONSTRAINT PK_DIACHINCC PRIMARY KEY (mancc, diachi)
)

CREATE TABLE DIENTHOAINCC (
	mancc VARCHAR(10) NOT NULL,
	dienthoai VARCHAR(20) NOT NULL,
	CONSTRAINT PK_DIENTHOAI PRIMARY KEY (mancc, dienthoai)
)

CREATE TABLE EMAILNCC (
	mancc VARCHAR(10) NOT NULL,
	email NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_EMAILNCC PRIMARY KEY (mancc, email)
)

CREATE TABLE HOADON (
	mahd VARCHAR(10) PRIMARY KEY,
	ngayhd DATETIME NOT NULL,
	makh VARCHAR(10) NOT NULL
)

CREATE TABLE THUCDON (
	id VARCHAR(6) PRIMARY KEY,
	tenmon NVARCHAR(50) NOT NULL,
	dongia INT NOT NULL,
	maloaitd VARCHAR(6) NOT NULL
)

CREATE TABLE HOADON_THUCDON (
	mahd VARCHAR(10) NOT NULL,
	id VARCHAR(6) NOT NULL,
	CONSTRAINT PK_HDTD PRIMARY KEY (mahd, id)
)

CREATE TABLE LOAITD (
	maloaitd VARCHAR(6) PRIMARY KEY,
	tenloai NVARCHAR(50) NOT NULL
)

CREATE TABLE KHACHHANG (
	makh VARCHAR(10) PRIMARY KEY,
	ten NVARCHAR(30),
	gioitinh NVARCHAR(10),
	sdt VARCHAR(20)
)

CREATE TABLE DONDATHANG (
	madh VARCHAR(10) PRIMARY KEY,
	ngaydh DATE NOT NULL,
	makh VARCHAR(10) NOT NULL,
	manv VARCHAR(10) NOT NULL
)

CREATE TABLE TTDONHANG (
	stt_dh INT IDENTITY(1,1) PRIMARY KEY,
	ngay DATETIME NOT NULL,
	tinhtrang NVARCHAR(30) NOT NULL,
	madh VARCHAR(10) NOT NULL
)

CREATE TABLE PHIEUGH (
	magh VARCHAR(10) PRIMARY KEY,
	ngaygh DATETIME NOT NULL,
	madh VARCHAR(10) NOT NULL
)

CREATE TABLE CHITIETDH (
	stt_dh INT IDENTITY PRIMARY KEY,
	dvt NVARCHAR(10),
	soluongdh INT NOT NULL,
	sotiendh INT NOT NULL,
	madh VARCHAR(10) NOT NULL,
	mahd VARCHAR(10) NOT NULL
)

CREATE TABLE CHITIETGH (
	stt_gh INT IDENTITY(1, 1) PRIMARY KEY,
	sotiengh INT NOT NULL,
	magh VARCHAR(10) NOT NULL,
	mahd VARCHAR(10) NOT NULL
)

CREATE TABLE CHITIETHD (
	stt_hd INT IDENTITY(1, 1) PRIMARY KEY,
	slhd INT NOT NULL,
	sotien INT NOT NULL,
	mahd VARCHAR(10) NOT NULL,
	maban VARCHAR(3)
)

CREATE TABLE BAN (
	maban VARCHAR(3) PRIMARY KEY,
	tenban NVARCHAR(6) NOT NULL,
	makv VARCHAR(5) NOT NULL
)

CREATE TABLE KHUVUC (
	makv VARCHAR(5) PRIMARY KEY,
	tenkv NVARCHAR(50) NOT NULL,
	macn VARCHAR(10) NOT NULL
)
GO

-- Tạo khóa ngoại bảng NHÂN VIÊN
ALTER TABLE NHANVIEN
ADD FOREIGN KEY (macn_thuocve) REFERENCES CHINHANH(macn)

ALTER TABLE NHANVIEN
ADD FOREIGN KEY (maca) REFERENCES CALAMVIEC(maca)

-- Tạo khóa ngoại bảng TÀI KHOẢN
ALTER TABLE TAIKHOAN
ADD FOREIGN KEY (manv) REFERENCES NHANVIEN(manv)

-- Tạo khóa ngoại bảng TỒN KHO
ALTER TABLE TONKHO
ADD FOREIGN KEY (manl) REFERENCES NGUYENLIEU(manl)

-- Tạo khóa ngoại bảng XUẤT NGUYÊN LIỆU
ALTER TABLE XUAT_NL
ADD FOREIGN KEY (manl) REFERENCES NGUYENLIEU(manl)

-- Tạo khóa ngoại bảng CT PHIẾU NHẬP
ALTER TABLE CHITIETPN
ADD FOREIGN KEY (manl) REFERENCES NGUYENLIEU(manl)

ALTER TABLE CHITIETPN
ADD FOREIGN KEY (mapn) REFERENCES PHIEUNHAP(mapn)

-- Tạo khóa ngoại bảng PHIẾU NHẬP
ALTER TABLE PHIEUNHAP
ADD FOREIGN KEY (mancc) REFERENCES NHACUNGCAP(mancc)

-- Tạo khóa ngoại bảng HÓA ĐƠN
ALTER TABLE HOADON
ADD FOREIGN KEY (makh) REFERENCES KHACHHANG(makh)

-- Tạo khóa ngoại bảng THỰC ĐƠN
ALTER TABLE THUCDON
ADD FOREIGN KEY (maloaitd) REFERENCES LOAITD(maloaitd)

-- Tạo khóa ngoại bảng ĐƠN ĐẶT HÀNG
ALTER TABLE DONDATHANG
ADD FOREIGN KEY (makh) REFERENCES KHACHHANG(makh)

ALTER TABLE DONDATHANG
ADD FOREIGN KEY (manv) REFERENCES NHANVIEN(manv)

-- Tạo khóa ngoại bảng TÌNH TRẠNG ĐƠN HÀNG
ALTER TABLE TTDONHANG
ADD FOREIGN KEY (madh) REFERENCES DONDATHANG(madh)

-- Tạo khóa ngoại bảng PHIẾU GIAO HÀNG
ALTER TABLE PHIEUGH
ADD FOREIGN KEY (madh) REFERENCES DONDATHANG(madh)

-- Tạo khóa ngoại bảng CHI TIẾT ĐẶT HÀNG 
ALTER TABLE CHITIETDH
ADD FOREIGN KEY (madh) REFERENCES DONDATHANG(madh)

ALTER TABLE CHITIETDH
ADD FOREIGN KEY (mahd) REFERENCES HOADON(mahd)

-- Tạo khóa ngoại bảng CHI TIẾT GIAO HÀNG 
ALTER TABLE CHITIETGH
ADD FOREIGN KEY (magh) REFERENCES PHIEUGH(magh)

ALTER TABLE CHITIETGH
ADD FOREIGN KEY (mahd) REFERENCES HOADON(mahd)

-- Tạo khóa ngoại bảng CHI TIẾT HÓA ĐƠN 
ALTER TABLE CHITIETHD
ADD FOREIGN KEY (mahd) REFERENCES HOADON(mahd)

ALTER TABLE CHITIETHD
ADD FOREIGN KEY (maban) REFERENCES BAN(maban)

-- Tạo khóa ngoại bảng BÀN 
ALTER TABLE BAN
ADD FOREIGN KEY (makv) REFERENCES KHUVUC(makv)

-- Tạo khóa ngoại bảng KHU VỰC 
ALTER TABLE KHUVUC
ADD FOREIGN KEY (macn) REFERENCES CHINHANH(macn)

-- Tạo khóa ngoại bảng HÓA ĐƠN_THỰC ĐƠN
ALTER TABLE HOADON_THUCDON
ADD FOREIGN KEY (mahd) REFERENCES HOADON(mahd)

ALTER TABLE HOADON_THUCDON
ADD FOREIGN KEY (id) REFERENCES THUCDON(id)

-- Tạo khóa ngoại bảng ĐỊA CHỈ NHÀ CUNG CẤP
ALTER TABLE DIACHINCC
ADD FOREIGN KEY (mancc) REFERENCES NHACUNGCAP(mancc)

-- Tạo khóa ngoại bảng ĐIỆN THOẠI NHÀ CUNG CẤP
ALTER TABLE DIENTHOAINCC
ADD FOREIGN KEY (mancc) REFERENCES NHACUNGCAP(mancc)

-- Tạo khóa ngoại bảng EMAIL NHÀ CUNG CẤP
ALTER TABLE EMAILNCC
ADD FOREIGN KEY (mancc) REFERENCES NHACUNGCAP(mancc)
GO

-- Tạo trigger kiểm soát hàng tồn kho khi xuất nguyên liệu
CREATE TRIGGER tg_tonkho ON XUAT_NL
AFTER INSERT
AS
BEGIN
	UPDATE TONKHO
	SET sl_hangton = sl_hangton - (
		SELECT sl_xuat
		FROM inserted
		WHERE manl = TONKHO.manl
	)
	FROM TONKHO JOIN inserted
	ON TONKHO.manl = inserted.manl
END
GO

-- Tạo trigger kiểm soát hàng tồn kho khi nhập nguyên liệu
CREATE TRIGGER tg_tonkho2 ON CHITIETPN
AFTER INSERT
AS
BEGIN
	UPDATE TONKHO
	SET sl_hangton = sl_hangton + (
		SELECT slpn
		FROM inserted
		WHERE manl = TONKHO.manl
	)
	FROM TONKHO JOIN inserted
	ON TONKHO.manl = inserted.manl
END
GO

-- Trigger kiểm soát hàng tồn kho khi xóa Phiếu Nhập
CREATE TRIGGER trg_huy ON CHITIETPN
FOR DELETE 
AS
BEGIN
	UPDATE TONKHO
	SET sl_hangton =  sl_hangton - (
		SELECT slpn FROM deleted
		WHERE manl = TONKHO.manl
	)
	FROM TONKHO JOIN deleted
	ON TONKHO.manl = deleted.manl
END
GO

-- Trigger kiểm soát hàng tồn kho khi xóa Xuất Nguyên Liệu
CREATE TRIGGER trg_huy2 ON XUAT_NL
FOR DELETE 
AS
BEGIN
	UPDATE TONKHO
	SET sl_hangton =  sl_hangton + (
		SELECT sl_xuat FROM deleted
		WHERE manl = TONKHO.manl
	)
	FROM TONKHO JOIN deleted
	ON TONKHO.manl = deleted.manl
END
GO

-- Trigger kiểm soát hàng tồn kho khi cập nhật Phiếu Nhập
CREATE TRIGGER trg_update1 ON CHITIETPN
AFTER UPDATE 
AS
BEGIN
	UPDATE TONKHO
	SET sl_hangton =  sl_hangton + (
		SELECT slpn FROM inserted
		WHERE manl = TONKHO.manl
	) - (
		SELECT slpn FROM deleted
		WHERE manl = TONKHO.manl
	)
	FROM TONKHO JOIN deleted
	ON TONKHO.manl = deleted.manl
END
GO

-- Trigger kiểm soát hàng tồn kho khi cập nhật XUẤT NGUYÊN LIỆU
CREATE TRIGGER trg_update2 ON XUAT_NL
AFTER UPDATE 
AS
BEGIN
	UPDATE TONKHO
	SET sl_hangton =  sl_hangton - (
		SELECT sl_xuat FROM inserted
		WHERE manl = TONKHO.manl
	) + (
		SELECT sl_xuat FROM deleted
		WHERE manl = TONKHO.manl
	)
	FROM TONKHO JOIN deleted
	ON TONKHO.manl = deleted.manl
END
GO
